"""Initial migration with users, papers, saved_papers, search_alerts

Revision ID: fc7b40e75078
Revises: 
Create Date: 2026-05-08 14:13:41.674209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7b40e75078'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('arxiv_id', sa.String(length=64), nullable=True),
    sa.Column('pubmed_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_normalized', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('is_open_access', sa.Boolean(), nullable=False),
    sa.Column('landing_url', sa.Text(), nullable=True),
    sa.Column('oa_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=True)
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=True)
    op.create_index(op.f('ix_papers_pubmed_id'), 'papers', ['pubmed_id'], unique=False)
    op.create_index(op.f('ix_papers_source'), 'papers', ['source'], unique=False)
    op.create_index(op.f('ix_papers_title_normalized'), 'papers', ['title_normalized'], unique=False)
    op.create_index(op.f('ix_papers_year'), 'papers', ['year'], unique=False)
    op.create_table('saved_papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('arxiv_id', sa.String(length=64), nullable=True),
    sa.Column('pubmed_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=512), nullable=True),
    sa.Column('publisher', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('is_open_access', sa.Boolean(), nullable=False),
    sa.Column('landing_url', sa.Text(), nullable=True),
    sa.Column('oa_url', sa.Text(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_papers_arxiv_id'), 'saved_papers', ['arxiv_id'], unique=False)
    op.create_index(op.f('ix_saved_papers_doi'), 'saved_papers', ['doi'], unique=False)
    op.create_index(op.f('ix_saved_papers_pubmed_id'), 'saved_papers', ['pubmed_id'], unique=False)
    op.create_index(op.f('ix_saved_papers_year'), 'saved_papers', ['year'], unique=False)
    op.create_table('search_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('search_alerts')
    op.drop_index(op.f('ix_saved_papers_year'), table_name='saved_papers')
    op.drop_index(op.f('ix_saved_papers_pubmed_id'), table_name='saved_papers')
    op.drop_index(op.f('ix_saved_papers_doi'), table_name='saved_papers')
    op.drop_index(op.f('ix_saved_papers_arxiv_id'), table_name='saved_papers')
    op.drop_table('saved_papers')
    op.drop_index(op.f('ix_papers_year'), table_name='papers')
    op.drop_index(op.f('ix_papers_title_normalized'), table_name='papers')
    op.drop_index(op.f('ix_papers_source'), table_name='papers')
    op.drop_index(op.f('ix_papers_pubmed_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
